### ISSUE TITLE
Failed to code sign "Markoff"

### ISSUE THREAD

**Issue by darkn3rd** [kaishin/markoff#30]
Is this normal, I opened the project in XCode, to see if I can figure out why Markoff from AppStore cannot open files with .md extension:

```
No valid signing identities (i.e. certificate and private key pair) matching the team ID “8E7TQ638ZD” were found.

Xcode can attempt to fix this issue. This will reset your code signing and provisioning settings to recommended values and resolve issues with signing identities and provisioning profiles.
```

How can one compile this project?  Are there any instructions or documentation?

**Comment by squarefrog** [comment]
The quickest way to build is to ignore code signing:

- Click on the target, then Build Settings
- Search for `Code Signing Identity` and click on the row to highlight it
- Press the backspace key to remove the old certificate identity
- Build and run.

**Comment by kaishin** [comment]
You can always change to your own signing config. I will be closing this for now.
