### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by vlad-at-work** [kaishin/markoff#37]
I'm installing on El Capitan if it matters. I got Xcode installed and when I run

`carthage update --platform mac` in root of the Markoff folder I get this output:

> **\* Fetching SwiftMark
> **\* Fetching ReactiveCocoa
> **\* Fetching Result
> **\* Checking out Result at "2.1.3"
> **\* Checking out ReactiveCocoa at "v4.2.2"
> **\* Checking out SwiftMark at "0.9"
> **\* xcodebuild output can be found in /var/folders/v0/2q6ncqbj72sc84_f2gzzwqd40000gn/T/carthage-xcodebuild.9jRZoo.log
> A shell task (/usr/bin/xcrun xcodebuild -project /Users/vladdy/tools/Software/Markoff/Carthage/Checkouts/Result/Result.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
> xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

Seems like it's got something to do with Xcode.

**Comment by kaishin** [comment]
Moving to SPM in 2.0, and that should solve this issue. You can already check the `markoff-2` branch.
