### ISSUE TITLE
Crashes on startup on High Sierra

### ISSUE THREAD

**Issue by cix** [kaishin/markoff#44]
Markoff stopped working when I upgraded to High Sierra. It no longer can be used to open .md files, and trying to open the Markoff application from the launcher produces a "Markoff quit unexpectedly" crash report.

This is the current version available through the Mac App Store. 1.0.1, I believe. I tried uninstalling it and installing again; same thing happens. I'm attaching the crash details here in a [text file](https://github.com/thoughtbot/Markoff/files/1517011/crash.txt).

I hope this can be fixed. And thank you for this little app, it is lovely, I'm going to miss it very much.

**Comment by rambo-panda** [comment]
I have the same problem！

**Comment by Nek** [comment]
I have the problem on macOS Sierra.

**Comment by jhbuhrman** [comment]
Ditto

**Comment by kaishin** [comment]
Known issue. Please check the list of issues for other duplicates. `2.0` will get this sorted out but won't likely be distributed through the app store.
