### ISSUE TITLE
Won't open .md files, only .sh files

### ISSUE THREAD

**Issue by mattolenik** [kaishin/Markoff#46]
Screenshot shows everything. I cannot open any .md files. Strangely .sh is the only thing I can open. I'm on High Sierra 10.13.3 and installed Markoff from the app store.

![borked](https://ibin.co/3uKtGnJf04Fg.png)

**Comment by PaulMcInnis** [comment]
I uninstalled after encountering this issue, read all the duplicate issues and it appears to have existed for 2 whole years. Please fix this!

**Comment by mattolenik** [comment]
Are you absolutely sure? Nothing has actually changed in the code.

I'm pretty sure we can just write this whole project off as dead. It's been obviously broken for years which means even Thoughtbot isn't using it internally anymore.

**Comment by kaishin** [comment]
This being a open source project means that there is no guarantee about features, fixing issues, etc. If you can open a PR I'd be very happy to review them and merge them, otherwise let's keep the discussion constructive.

**Comment by ryanmerolle** [comment]
Is .md support intended?  Seems like a function that we would want from the start.  It does not work for me using the current app store version.

**Comment by mattolenik** [comment]
I'm not sure how I can be more constructive. The primary feature of the program is literally broken, it cannot be used. Have you tried it? If you want to just ignore what people are saying, close the bug, don't just gaslight everyone and ask us to fix the primary purpose of the program with a PR.
