### ISSUE TITLE
sharplet/Quick.git repository no longer exists

### ISSUE THREAD

**Issue by vaskaloidis** [kaishin/markoff#49]
Install throws an error because the repository `https://github.com/sharplet/Quick.git` does not exist anymore 

Nemesis:Markoff-master vas$ carthage update --platform mac
*** Cloning ReactiveCocoa
*** Cloning SwiftMark
*** Cloning Result
*** Checking out SwiftMark at "0.9"
*** Checking out ReactiveCocoa at "v4.2.2"
*** Checking out Result at "2.1.3"
A shell task (/usr/bin/env git clone --quiet https://github.com/sharplet/Quick.git /Users/vas/Downloads/Markoff-master/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick) failed with exit code 128:
remote: Repository not found.
fatal: repository 'https://github.com/sharplet/Quick.git/' not found

**Comment by vaskaloidis** [comment]
It is probably renamed to something else I would assume, but without knowing what the use for that project was (because I can't find the docs for Quick), I am not able to easily find the renamed repository, and don't have time to do any super deep reverse engineering. Just wanted to mention the bug. Thanks.

**Comment by vaskaloidis** [comment]
And after a little searching - this may be the branch that you need `https://github.com/Quick/Quick/tree/as-qck-generate-main` - the contributor `sharplet` submitted a PR, and you previously had linked to a repo of his. Don't have time to test any of this and submit a PR, but I figured I would mention it incase you needed something specifically form a fork he may have deleted or something.

**Comment by kaishin** [comment]
I dropped the dependency on 2.0 (see `markoff-2.0` branch).
