### ISSUE TITLE
Code block language name !=  all low caps, syntax highlighting turns off and idents first line of code block

### ISSUE THREAD

**Issue by d-cas** [kaishin/markoff#54]
[Gif of problem](https://imgur.com/a/03G3ykxl)

![](https://i.imgur.com/rKXbWJi.gif)

**Comment by kaishin** [comment]
I do not see Markoff in the attached gif. Closing but please reopen if you have more information.

**Comment by d-cas** [comment]
GIF did not render correctly. Will post a properly-rendered GIF if I can recreate the bug.

**Comment by d-cas** [comment]
You can see bug [here](https://imgur.com/AhU8aIB)

https://imgur.com/AhU8aIB

**Comment by kaishin** [comment]
Thank you for reporting.
